disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Urtzi Enriquez-Urzelai"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_inverted.png"
  secondaryLogo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Urtzi Enriquez-Urzelai"
  email = "uenriquez@proton.me"
  image = "img/picture.jpg"
  imageQuality = 96
  headline = "Physiology, ecology and modeling in a changing world"
  bio = "Physiological and evolutionary ecologist"
  links = [
    { email = "mailto:uenriquez@proton.me" },
    { google = "https://scholar.google.com/citations?user=4fPSob0AAAAJ&hl=en" },
    { orcid = "https://orcid.org/0000-0001-5958-2250" },
    { researchgate = "https://www.researchgate.net/profile/Urtzi-Enriquez-Urzelai" },
    { github = "https://github.com/urtzienriquez" },
    { codeberg = "https://codeberg.org/urtzienriquez"},
  ]
